server:
  port: 8080

spring:
  application:
    name: starwars
  cloud:
    openfeign:
      client:
        swapi: https://swapi.dev/api
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=5m,initialCapacity=50

springdoc:
  api-docs:
    path: /swagger-ui/swagger-config


management:
  endpoints:
    web:
      exposure:
        include: health, info, caches

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000

resilience4j:
  circuitbreaker:
    instances:
      CircuitBreakerGeneral:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
        registerHealthIndicator: true