openapi: 3.0.3
info:
  title: swapi.dev models
  description: Models specification for https://swapi.dev/
  version: 1.0.0

paths: { }

components:
  schemas:

    PeopleSearchResult:
      description: List of people returned
      type: object
      properties:
        count:
          type: integer
        next:
          type: string
          format: uri
        previous:
          type: string
          format: uri
        results:
          type: array
          items:
            $ref: '#/components/schemas/People'

    People:
      description: A person within the Star Wars universe
      type: object
      properties:
        name:
          type: string
          description: The name of this person.
        height:
          type: string
          description: The height of this person in meters.
        mass:
          type: string
          description: The mass of this person in kilograms.
        hair_color:
          type: string
          description: The hair color of this person.
        skin_color:
          type: string
          description: The skin color of this person.
        eye_color:
          type: string
          description: The eye color of this person.
        birth_year:
          type: string
          description: The birth year of this person. BBY (Before the Battle of Yavin) or ABY (After the Battle of Yavin).
        gender:
          type: string
          description: The gender of this person (if known).
        homeworld:
          type: string
          format: uri
          description: The url of the planet resource that this person was born on.
        films:
          type: array
          items:
            type: string
            format: uri
          description: An array of urls of film resources that this person has been in.
        species:
          type: array
          items:
            type: string
            format: uri
          description: The url of the species resource that this person is.
        vehicles:
          type: array
          items:
            type: string
            format: uri
          description: An array of vehicle resources that this person has piloted
        starships:
          type: array
          items:
            type: string
            format: uri
          description: An array of starship resources that this person has piloted
        url:
          type: string
          format: uri
          description: The url of this resource
        created:
          type: string
          format: date-time
          description: The ISO 8601 date format of the time that this resource was created.
        edited:
          type: string
          format: date-time
          description: the ISO 8601 date format of the time that this resource was edited.

    VehicleSearchResult:
      description: List of vehicles returned
      type: object
      properties:
        count:
          type: integer
        next:
          type: string
          format: uri
        previous:
          type: string
          format: uri
        results:
          type: array
          items:
            $ref: '#/components/schemas/Vehicle'

    Vehicle:
      description: A vehicle.
      type: object
      properties:
        name:
          type: string
          description: The name of this vehicle. The common name, such as Sand Crawler.
        model:
          type: string
          description: The model or official name of this vehicle. Such as All Terrain Attack Transport.
        manufacturer:
          type: string
          description: The manufacturer of this vehicle. Comma separated if more than one.
        cost_in_credits:
          type: string
          description: The cost of this vehicle new, in galactic credits.
        length:
          type: string
          description: The length of this vehicle in meters.
        crew:
          type: string
          description: The number of personnel needed to run or pilot this vehicle.
        passengers:
          type: string
          description: The number of non-essential people this vehicle can transport.
        max_atmosphering_speed:
          type: string
          description: The maximum speed of this vehicle in atmosphere.
        cargo_capacity:
          type: string
          description: The maximum number of kilograms that this vehicle can transport.
        consumables:
          type: string
          description: The maximum length of time that this vehicle can provide consumables for its entire crew without having to resupply.
        hyperdrive_rating:
          type: string
        MGLT:
          type: string
        starship_class":
          type: string
        films:
          type: array
          items:
            type: string
            format: uri
          description: An array of Film URL Resources that this vehicle has appeared in.
        pilots:
          type: array
          items:
            type: string
            format: uri
          description: An array of People URL Resources that this vehicle has been piloted by.
        url:
          type: string
          format: uri
          description: The hypermedia URL of this resource.
        created:
          type: string
          format: date-time
          description: The ISO 8601 date format of the time that this resource was created.
        edited:
          type: string
          format: date-time
          description: the ISO 8601 date format of the time that this resource was edited.

    FilmsSearchResult:
      description: List of films returned
      type: object
      properties:
        count:
          type: integer
        next:
          type: string
          format: uri
        previous:
          type: string
          format: uri
        results:
          type: array
          items:
            $ref: '#/components/schemas/Film'

    Film:
      description: A Star Wars film
      type: object
      properties:
        title:
          type: string
          description: The title of this film.
        episode_id:
          type: integer
          description: The episode number of this film.
        opening_crawl:
          type: string
          description: The opening crawl text at the beginning of this film.
        director:
          type: string
          description: The director of this film.
        producer:
          type: string
          description: The producer(s) of this film.
        release_date:
          type: string
          description: The release date at original creator country.
        characters:
          type: array
          items:
            type: string
            format: uri
          description: The people resources featured within this film.
        planets:
          type: array
          items:
            type: string
            format: uri
          description: The planet resources featured within this film.
        starships:
          type: array
          items:
            type: string
            format: uri
          description: The starship resources featured within this film.
        vehicles:
          type: array
          items:
            type: string
            format: uri
          description: The vehicle resources featured within this film.
        species:
          type: array
          items:
            type: string
            format: uri
          description: The species resources featured within this film.
        url:
          type: string
          format: uri
          description: The url of this resource
        created:
          type: string
          format: date-time
          description: The ISO 8601 date format of the time that this resource was created.
        edited:
          type: string
          format: date-time
          description: the ISO 8601 date format of the time that this resource was edited.

    Planet:
      description: A planet.
      type: object
      properties:
        name:
          type: string
          description: The name of this planet.
        diameter:
          type: string
          description: The diameter of this planet in kilometers.
        rotation_period:
          type: string
          description: The number of standard hours it takes for this planet to complete a single rotation on its axis.
        orbital_period:
          type: string
          description: The number of standard days it takes for this planet to complete a single orbit of its local star.
        gravity:
          type: string
          description: A number denoting the gravity of this planet. Where 1 is normal.
        population:
          type: string
          description: The average populationof sentient beings inhabiting this planet.
        climate:
          type: string
          description: The climate of this planet. Comma-seperated if diverse.
        terrain:
          type: string
          description: the terrain of this planet. Comma-seperated if diverse.
        surface_water:
          type: string
          description: The percentage of the planet surface that is naturally occuring water or bodies of water.
        films:
          type: array
          items:
            type: string
            format: uri
          description: An array of Film URL Resources that this planet has appeared in.
        residents:
          type: array
          items:
            type: string
            format: uri
          description: An array of People URL Resources that live on this planet.
        url:
          type: string
          format: uri
          description: The hypermedia URL of this resource.
        created:
          type: string
          format: date-time
          description: The ISO 8601 date format of the time that this resource was created.
        edited:
          type: string
          format: date-time
          description: the ISO 8601 date format of the time that this resource was edited.
