apiVersion: apps/v1
kind: Deployment
metadata:
  name: swapi-app
  labels:
    app: swapi-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swapi-app
  template:
    metadata:
      labels:
        app: swapi-app
    spec:
      containers:
      - name: swapi-container
        image: jlseminara/swapi-service:latest
        ports:
        - containerPort: 8080
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Ensures at least 2 pods are available during updates
      maxSurge: 1

---

apiVersion: v1
kind: Service
metadata:
  name: swapi-kbntsrv
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 32000
  selector:
    app: swapi-app